### ISSUE TITLE
On /Reload MixxitPlugin an Exception is thrown while trying to load the plugin.

### ISSUE THREAD

**Issue by ghost** [mixxit/MixxitPlugin#2]
[INFO] Command used by zkzeroxvirus /reloadplugin mixxitplugin
2010-10-28 18:22:57 [SEVERE] Exception while loading plugin
java.lang.ClassNotFoundException: mixxitplugin
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at PluginLoader.load(PluginLoader.java:174)
    at PluginLoader.reloadPlugin(PluginLoader.java:162)
    at id.d(id.java:1035)
    at id.a(id.java:356)
    at ba.a(SourceFile:24)
    at bb.a(SourceFile:218)
    at id.a(id.java:53)
    at dc.a(SourceFile:85)
    at net.minecraft.server.MinecraftServer.h(SourceFile:264)
    at net.minecraft.server.MinecraftServer.run(SourceFile:205)
    at bm.run(SourceFile:480)

I got this While trying to /reloadplugin MixxitPlugin.
- zkzeroxvirus

**Comment by ghost** [comment]
Seems the player that reported this tried the reload a non existent plugin (name was in all lower case). 

Not a bug with MixxitPlugin, closing issue.
